[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "pnpm start"
# healthcheckPath = "/api/health"
healthcheckTimeout = 60

[env]
NODE_ENV = "production"
# PORT = "5000"
